name: pages build and deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  build-and-deploy: 
    name: Deploy docs using mkdocs gh-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9 #
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Build and Deploy docs
        run: mkdocs gh-deploy --force --clean
