name: Simple Action Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_job:
    name: Run a simple command
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Simple workflow triggered successfully!"
