name: Update development schedule

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install PyYAML
      - name: Refresh dev schedule
        run: python scripts/update_dev_schedule.py
      - name: Commit updated schedule
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/dev-schedule.md
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update dev schedule"
            git push
          fi
